apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-mysql-deployment
  template:
    metadata:
      labels:
        app: database-mysql-deployment
    spec:
      containers:
        - name: mysql-image
          image: mysql
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-mysql-secret
                  key: password
          args: ["--default-authentication-plugin=mysql_native_password"]
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: database-mysql-pvc
      restartPolicy: Always
      volumes:
        - name: database-mysql-pvc
          persistentVolumeClaim:
            claimName: database-mysql-pvc
