apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
spec:
  selector:
    matchLabels:
      app: php-app-deployment
  template:
    metadata:
      labels:
        app: php-app-deployment
    spec:
      containers:
        - name: php-app-image
          image: linx/php80
          imagePullPolicy: Never
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 9000
          env:
            - name: APP_ENV
              value: prod
            - name: APP_SECRET
              value: c055390293f4df5f6436b4a9d0f544ac
            - name: DATABASE_URL
              value: 'mysql://root:Linx@2021@database-mysql-service:3306/sf_linx?serverVersion=8.0'
            - name: CORS_ALLOW_ORIGIN
              value: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
            - name: REDIS_HOST
              value: redis://redis-master
            - name: DB_HOST
              value: mysql-service
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-mysql-secret
                  key: password
          volumeMounts:
            - mountPath: /var/www/html
              name: php-app-pvc
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html && chown -R www-data:www-data /var/www/html && chmod -R 777 /var/www/html/var"]
      restartPolicy: Always
      volumes:
        - name: php-app-pvc
          persistentVolumeClaim:
            claimName: php-app-pvc
